USE project314;

CREATE TABLE users (username varchar(14) NOT NULL, password varchar(20) NOT NULL, role varchar(20), PRIMARY KEY(username));

INSERT INTO users VALUE ("owner01", "pwdisowner01", "owner"), ("owner02", "pwdisowner02", "owner"), ("manager01", "pwdismanager01", "manager"), ("manager02", "pwdismanager02", "manager"), ("manager03", "pwdismanager03", "manager"), 
						 ("manager04", "pwdismanager04", "manager"), ("manager05", "pwdismanager05", "manager"), ("staff01", "pwdisstaff01", "staff"), ("staff02", "pwdisstaff02", "staff"), ("staff03", "pwdisstaff03", "staff"), ("staff04", "pwdisstaff04", "staff"), 
                         ("staff05", "pwdisstaff05", "staff"), ("staff06", "pwdisstaff06", "staff"), ("staff07", "pwdisstaff07", "staff"), ("staff08", "pwdisstaff08", "staff"), ("staff09", "pwdisstaff09", "staff"), ("staff10", "pwdisstaff10", "staff"), ("staff11", "pwdisstaff11", "staff"), 
                         ("staff12", "pwdisstaff12", "staff"), ("staff13", "pwdisstaff13", "staff"), ("staff14", "pwdisstaff14", "staff"), ("staff15", "pwdisstaff15", "staff"), ("staff16", "pwdisstaff16", "staff"), ("staff17", "pwdisstaff17", "staff"), ("staff18", "pwdisstaff18", "staff"), 
                         ("staff19", "pwdisstaff19", "staff"), ("staff20", "pwdisstaff20", "staff"), ("staff21", "pwdisstaff21", "staff"), ("staff22", "pwdisstaff22", "staff"), ("staff23", "pwdisstaff23", "staff"), ("staff24", "pwdisstaff24", "staff"), ("staff25", "pwdisstaff25", "staff"), 
                         ("staff26", "pwdisstaff26", "staff"), ("staff27", "pwdisstaff27", "staff"), ("staff28", "pwdisstaff28", "staff"), ("staff29", "pwdisstaff29", "staff"), ("staff30", "pwdisstaff30", "staff"), ("staff31", "pwdisstaff31", "staff"), ("staff32", "pwdisstaff32", "staff"), 
                         ("staff33", "pwdisstaff33", "staff"), ("staff34", "pwdisstaff34", "staff"), ("staff35", "pwdisstaff35", "staff"), ("staff36", "pwdisstaff36", "staff"), ("staff37", "pwdisstaff37", "staff"), ("staff38", "pwdisstaff38", "staff"), ("staff39", "pwdisstaff39", "staff"), 
                         ("staff40", "pwdisstaff40", "staff"), ("staff41", "pwdisstaff41", "staff"), ("staff42", "pwdisstaff42", "staff"), ("staff43", "pwdisstaff43", "staff"), ("staff44", "pwdisstaff44", "staff"), ("staff45", "pwdisstaff45", "staff"), ("staff46", "pwdisstaff46", "staff"), 
                         ("staff47", "pwdisstaff47", "staff"), ("staff48", "pwdisstaff48", "staff"), ("staff49", "pwdisstaff49", "staff"), ("staff50", "pwdisstaff50", "staff"), ("staff51", "pwdisstaff51", "staff"), ("staff52", "pwdisstaff52", "staff"), ("staff53", "pwdisstaff53", "staff"), 
                         ("staff54", "pwdisstaff54", "staff"), ("staff55", "pwdisstaff55", "staff"), ("staff56", "pwdisstaff56", "staff"), ("staff57", "pwdisstaff57", "staff"), ("staff58", "pwdisstaff58", "staff"), ("staff59", "pwdisstaff59", "staff"), ("staff60", "pwdisstaff60", "staff"), 
                         ("staff61", "pwdisstaff61", "staff"), ("staff62", "pwdisstaff62", "staff"), ("staff63", "pwdisstaff63", "staff"), ("staff64", "pwdisstaff64", "staff"), ("staff65", "pwdisstaff65", "staff"), ("staff66", "pwdisstaff66", "staff"), ("staff67", "pwdisstaff67", "staff"), 
                         ("staff68", "pwdisstaff68", "staff"), ("staff69", "pwdisstaff69", "staff"), ("staff70", "pwdisstaff70", "staff"), ("staff71", "pwdisstaff71", "staff"), ("staff72", "pwdisstaff72", "staff"), ("staff73", "pwdisstaff73", "staff"), ("staff74", "pwdisstaff74", "staff"),
                         ("staff75", "pwdisstaff75", "staff"), ("staff76", "pwdisstaff76", "staff"), ("staff77", "pwdisstaff77", "staff"), ("staff78", "pwdisstaff78", "staff"), ("staff79", "pwdisstaff79", "staff"), ("staff80", "pwdisstaff80", "staff"), ("staff81", "pwdisstaff81", "staff"), 
                         ("staff82", "pwdisstaff82", "staff"), ("staff83", "pwdisstaff83", "staff"), ("staff84", "pwdisstaff84", "staff"), ("staff85", "pwdisstaff85", "staff"), ("staff86", "pwdisstaff86", "staff"), ("staff87", "pwdisstaff87", "staff"), ("staff88", "pwdisstaff88", "staff"),
                         ("userAdmin01", "pwdisuserAdmin01", "userAdmin"), ("userAdmin02", "pwdisuserAdmin02", "userAdmin"), ("userAdmin03", "pwdisuserAdmin03", "userAdmin"),  ("userAdmin04", "pwdisuserAdmin04", "userAdmin"), ("userAdmin05", "pwdisuserAdmin05", "userAdmin");